### PR TITLE
Add `ModSearchQuery#modLoaderTypes`

### PR DESCRIPTION
**Pull request by PaintNinja**
Allows filtering by a list of mod loader types.

https://docs.curseforge.com/#search-mods:~:text=modLoaderTypes%3A%20Filter%20by%20a%20list%20of%20mod%20loader%20types

### CODE REVIEW

**Comment by Matyrobbrt** [comment]
Can you add a test for this? The docs don't mention the on-command separation of the list so it's good to make sure that it won't change without being noticed in the future.

**Comment by PaintNinja** [comment]
I'm not sure what you're referring to by "on-command separation of the list"?

**Comment by Matyrobbrt** [comment]
I meant on-comma, great typo.

**Comment by PaintNinja** [comment]
Added a test

**Review by Matyrobbrt — APPROVED** [review]

**Pull request merged**
